# Generated by Django 4.1.5 on 2023-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, help_text='upload image', null=True, upload_to='uploads/'),
        ),
    ]
