# Generated by Django 4.1.5 on 2023-07-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='highest_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_price', to='auctions.auction'),
        ),
    ]
